# Generated by Django 6.0.5 on 2026-06-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_remove_work_place_supervisor_user_academicsupervisor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklylog',
            options={'ordering': ['-id']},
        ),
    ]
