# Generated by Django 6.0.5 on 2026-06-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='week_number',
            field=models.IntegerField(db_index=True),
        ),
    ]
