# Generated by Django 6.0.5 on 2026-06-09 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed (e.g., 'SUBMIT_LOG', 'APPROVE_LOG')", max_length=100)),
                ('object_type', models.CharField(help_text="Model name (e.g., 'WeeklyLog')", max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the affected object')),
                ('previous_state', models.JSONField(blank=True, help_text='State before change', null=True)),
                ('new_state', models.JSONField(blank=True, help_text='State after change', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
