# Generated by Django 6.0.4 on 2026-06-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company where internship takes place', max_length=100)),
                ('position', models.CharField(blank=True, help_text='Role or position during internship', max_length=100, null=True)),
                ('start_date', models.DateField(help_text='Start date of the internship')),
                ('end_date', models.DateField(help_text='End date of the internship')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the placement is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the placement was created')),
                ('academic_supervisor', models.ForeignKey(help_text='Supervisor from the academic institution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_placements', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(help_text='The student assigned to this placement', on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='accounts.student')),
                ('workplace_supervisor', models.ForeignKey(help_text='Supervisor at the workplace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
