# Generated by Django 6.0.5 on 2026-06-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('assessment', 'Assessment Feedback'), ('evaluation', 'Evaluation Feedback'), ('log_reviewed', 'Log Reviewed'), ('log_approved', 'Log Approved'), ('placement', 'Placement Update')], db_index=True, max_length=50, null=True),
        ),
    ]
