# Generated by Django 6.0.5 on 2026-06-09 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.IntegerField(default=10)),
                ('weight_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Weight (e.g., 40.00 for 40%)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('communication_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('professionalism_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated total score', max_digits=5, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('academic_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_supervisor', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship_evaluations', to=settings.AUTH_USER_MODEL)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='logs.weeklylog')),
                ('weekly_log', models.OneToOneField(blank=True, help_text='The weekly log being evaluated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='logs.weeklylog')),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcriteria')),
            ],
        ),
    ]
